### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by Onager** [log2timeline/dftimewolf#19]
Traceback:
```
Running linter on changed files.
ERROR: No valid .dftimewolfrc file found. See README for details.
test_dftimewolf (unittest.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: test_dftimewolf (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_dftimewolf
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/onager/code/onager_dftimewolf/tests/test_dftimewolf.py", line 5, in <module>
    from dftimewolf.cli import dftimewolf_recipes
  File "/home/onager/code/onager_dftimewolf/dftimewolf/cli/dftimewolf_recipes.py", line 44, in <module>
    MODULES = import_modules()
  File "/home/onager/code/onager_dftimewolf/dftimewolf/internals.py", line 49, in import_modules
    module_directories = get_config()['module_dirs']
  File "/home/onager/code/onager_dftimewolf/dftimewolf/internals.py", line 131, in get_config
    exit(-1)
  File "/home/onager/code/venvs/plaso/lib/python2.7/site.py", line 403, in __call__
    raise SystemExit(code)
SystemExit: -1

```

**Comment by tomchop** [comment]
Fixed in fc65d0415ccfc9a009c7352171a008f7157346ef
