### ISSUE TITLE
CI test failing due to ModuleNotFoundError: No module named 'google.api_core.client_options'

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dftimewolf#200]
https://travis-ci.org/log2timeline/dftimewolf/jobs/565314908

```
======================================================================
ERROR: lib.processors.turbinia (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: lib.processors.turbinia
Traceback (most recent call last):
  File "/opt/python/3.6.7/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/python/3.6.7/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/log2timeline/dftimewolf/tests/lib/processors/turbinia.py", line 19, in <module>
    from dftimewolf.lib.processors import turbinia
  File "./dftimewolf/lib/processors/turbinia.py", line 11, in <module>
    from turbinia import client as turbinia_client
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/turbinia/client.py", line 31, in <module>
    from turbinia import task_manager
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/turbinia/task_manager.py", line 35, in <module>
    from google.cloud import pubsub
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/google/cloud/pubsub.py", line 20, in <module>
    from google.cloud.pubsub_v1 import PublisherClient
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/google/cloud/pubsub_v1/__init__.py", line 18, in <module>
    from google.cloud.pubsub_v1 import publisher
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/google/cloud/pubsub_v1/publisher/__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1.publisher.client import Client
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/google/cloud/pubsub_v1/publisher/client.py", line 29, in <module>
    from google.cloud.pubsub_v1.gapic import publisher_client
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/google/cloud/pubsub_v1/gapic/publisher_client.py", line 27, in <module>
    import google.api_core.client_options
ModuleNotFoundError: No module named 'google.api_core.client_options'
```

**Comment by tomchop** [comment]
Closing as CI test works now
