### ISSUE TITLE
Error uploading plaso file to timesketch server

### ISSUE THREAD

**Issue by reddevillz** [log2timeline/dftimewolf#324]
Getting the following error when trying to run "dftimewold upload_ts file.plaso" command. DFtimewolf version is the latest.

[2020-08-17 20:21:55,539] [dftimewolf          ] INFO     Logging to stdout and /tmp/dftimewolf.log
[2020-08-17 20:21:55,539] [dftimewolf          ] DEBUG    Recipe data path: /home/test/dftimewolf/dftimewolf/data
[2020-08-17 20:21:55,539] [dftimewolf          ] DEBUG    Configuration loaded from: /home/test/dftimewolf/dftimewolf/data/config.json
[2020-08-17 20:21:55,553] [dftimewolf          ] INFO     Loading recipe upload_ts...
[2020-08-17 20:21:55,554] [dftimewolf          ] INFO     Loaded recipe upload_ts with 2 modules
[2020-08-17 20:21:55,554] [dftimewolf          ] INFO     Running preflights...
[2020-08-17 20:21:55,554] [dftimewolf          ] INFO     Setting up modules...
[2020-08-17 20:21:55,555] [dftimewolf          ] INFO     Setting up module: FilesystemCollector
[2020-08-17 20:21:55,556] [dftimewolf          ] INFO     Setting up module: TimesketchExporter
[2020-08-17 20:21:55,557] [dftimewolf          ] CRITICAL An unknown error occurred in module TimesketchExporter: 'DFTimewolfState' object has no attribute 'ModuleError'
[2020-08-17 20:21:55,559] [dftimewolf          ] ERROR    dfTimewolf encountered one or more errors:
[2020-08-17 20:21:55,559] [dftimewolf          ] ERROR    1: error from state: An unknown error occurred in module TimesketchExporter: 'DFTimewolfState' object has no attribute 'Module
Error'
[2020-08-17 20:21:55,559] [dftimewolf          ] ERROR    Traceback (most recent call last):
[2020-08-17 20:21:55,560] [dftimewolf          ] ERROR      File "/usr/local/lib/python3.6/dist-packages/timesketch_api_client/crypto.py", line 155, in load_credentials
[2020-08-17 20:21:55,560] [dftimewolf          ] ERROR        password = config_assistant.get_config('cred_key')
[2020-08-17 20:21:55,560] [dftimewolf          ] ERROR      File "/usr/local/lib/python3.6/dist-packages/timesketch_api_client/config.py", line 155, in get_config
[2020-08-17 20:21:55,560] [dftimewolf          ] ERROR        return self._config[name]
[2020-08-17 20:21:55,560] [dftimewolf          ] ERROR    KeyError: 'cred_key'
[2020-08-17 20:21:55,560] [dftimewolf          ] ERROR    
[2020-08-17 20:21:55,560] [dftimewolf          ] ERROR    During handling of the above exception, another exception occurred:
[2020-08-17 20:21:55,561] [dftimewolf          ] ERROR    
[2020-08-17 20:21:55,561] [dftimewolf          ] ERROR    Traceback (most recent call last):
[2020-08-17 20:21:55,561] [dftimewolf          ] ERROR      File "/home/test/dftimewolf/dftimewolf/dftimewolf/lib/timesketch_utils.py", line 43, in GetApiClient
[2020-08-17 20:21:55,561] [dftimewolf          ] ERROR        config_assistant=assistant, token_password=token_password)
[2020-08-17 20:21:55,561] [dftimewolf          ] ERROR      File "/usr/local/lib/python3.6/dist-packages/timesketch_api_client/config.py", line 81, in configure_missing_parameters
[2020-08-17 20:21:55,561] [dftimewolf          ] ERROR        config_assistant=config_assistant, password=token_password)
[2020-08-17 20:21:55,561] [dftimewolf          ] ERROR      File "/usr/local/lib/python3.6/dist-packages/timesketch_api_client/crypto.py", line 160, in load_credentials
[2020-08-17 20:21:55,562] [dftimewolf          ] ERROR        'Not able to determine encryption key from config.')
[2020-08-17 20:21:55,562] [dftimewolf          ] ERROR    OSError: Not able to determine encryption key from config.
[2020-08-17 20:21:55,562] [dftimewolf          ] ERROR    
[2020-08-17 20:21:55,562] [dftimewolf          ] ERROR    During handling of the above exception, another exception occurred:
[2020-08-17 20:21:55,562] [dftimewolf          ] ERROR    
[2020-08-17 20:21:55,562] [dftimewolf          ] ERROR    Traceback (most recent call last):
[2020-08-17 20:21:55,562] [dftimewolf          ] ERROR      File "/home/test/dftimewolf/dftimewolf/dftimewolf/lib/state.py", line 170, in _SetupModuleThread
[2020-08-17 20:21:55,563] [dftimewolf          ] ERROR        module.SetUp(**new_args)
[2020-08-17 20:21:55,563] [dftimewolf          ] ERROR      File "/home/test/dftimewolf/dftimewolf/dftimewolf/lib/exporters/timesketch.py", line 57, in SetUp
[2020-08-17 20:21:55,563] [dftimewolf          ] ERROR        self.state, token_password=token_password)
[2020-08-17 20:21:55,563] [dftimewolf          ] ERROR      File "/home/test/dftimewolf/dftimewolf/dftimewolf/lib/timesketch_utils.py", line 45, in GetApiClient
[2020-08-17 20:21:55,563] [dftimewolf          ] ERROR        state.ModuleError(
[2020-08-17 20:21:55,563] [dftimewolf          ] ERROR    AttributeError: 'DFTimewolfState' object has no attribute 'ModuleError'
[2020-08-17 20:21:55,564] [dftimewolf          ] ERROR    
[2020-08-17 20:21:55,564] [dftimewolf          ] CRITICAL One or more unexpected errors occurred.
[2020-08-17 20:21:55,564] [dftimewolf          ] CRITICAL Please consider opening an issue: https://github.com/log2timeline/dftimewolf/issues/new
[2020-08-17 20:21:55,564] [dftimewolf          ] CRITICAL Critical error found. Aborting.

**Comment by kiddinn** [comment]
I think it is weird to see:
```
[2020-08-17 20:21:55,559] [dftimewolf ] ERROR 1: error from state: An unknown error occurred in module TimesketchExporter: 'DFTimewolfState' object has no attribute 'ModuleError'
```

That tells me that you may have two versions of the code.

However the main issue seems to be here:
```
[2020-08-17 20:21:55,562] [dftimewolf ] ERROR OSError: Not able to determine encryption key from config.
```

Was this the first time you were attempting to upload a plaso file?

Can you delete these two files if they exist:

```shell
$ rm ~/.timesketch.token
$ rm ~/.timesketchrc
```

And then try again. If that fails, then delete these two files and then use `timesketch_import_client` to upload the first file and then try dftimewolf again.

**Comment by reddevillz** [comment]
Can you help me what my response to the following should be?
What is the value for [auth_mode]:

**Comment by reddevillz** [comment]
@kiddinn Tried as requested. 
Getting the following error with "timesketch_import_client.py"

/usr/local/bin/timesketch_importer.py: line 14: A simple frontend to the Timesketch data importer.: command not found
from: can't read /var/mail/__future__
/usr/local/bin/timesketch_importer.py: line 17: import: command not found
/usr/local/bin/timesketch_importer.py: line 18: import: command not found
/usr/local/bin/timesketch_importer.py: line 19: import: command not found
/usr/local/bin/timesketch_importer.py: line 20: import: command not found
/usr/local/bin/timesketch_importer.py: line 21: import: command not found
from: can't read /var/mail/typing
from: can't read /var/mail/timesketch_api_client
from: can't read /var/mail/timesketch_api_client
from: can't read /var/mail/timesketch_api_client
from: can't read /var/mail/timesketch_api_client
from: can't read /var/mail/timesketch_api_client
from: can't read /var/mail/timesketch_import_client
from: can't read /var/mail/timesketch_import_client
/usr/local/bin/timesketch_importer.py: line 34: syntax error near unexpected token `level=os.environ.get'
/usr/local/bin/timesketch_importer.py: line 34: `logging.basicConfig(level=os.environ.get('LOGLEVEL', 'INFO'))'

**Comment by reddevillz** [comment]
More Errors related to Timesketch this time with TLS cert

dftimewolf gcp_logging_cloudaudit_ts project1 2020-08-01T00:00:00Z 2020-09-01T00:00:00Z
[2020-09-09 23:32:41,728] [dftimewolf          ] INFO     Logging to stdout and /tmp/dftimewolf.log
[2020-09-09 23:32:41,728] [dftimewolf          ] DEBUG    Recipe data path: /home/user1/dftimewolf/dftimewolf/data
[2020-09-09 23:32:41,729] [dftimewolf          ] DEBUG    Configuration loaded from: /home/user1/dftimewolf/dftimewolf/data/config.json
[2020-09-09 23:32:41,740] [dftimewolf          ] INFO     Loading recipe gcp_logging_cloudaudit_ts...
[2020-09-09 23:32:41,741] [dftimewolf          ] INFO     Loaded recipe gcp_logging_cloudaudit_ts with 3 modules
[2020-09-09 23:32:41,741] [dftimewolf          ] INFO     Running preflights...
[2020-09-09 23:32:41,742] [dftimewolf          ] INFO     Setting up modules...
[2020-09-09 23:32:41,742] [dftimewolf          ] INFO     Setting up module: GCPLogsCollector
[2020-09-09 23:32:41,743] [dftimewolf          ] INFO     Setting up module: GCPLoggingTimesketch
[2020-09-09 23:32:41,743] [dftimewolf          ] INFO     Setting up module: TimesketchExporter
[2020-09-09 23:32:41,903] [dftimewolf          ] **CRITICAL An unknown error occurred in module TimesketchExporter: Could not find a suitable TLS CA certificate bundle, invalid path: True**
[2020-09-09 23:32:41,929] [dftimewolf          ] ERROR    dfTimewolf encountered one or more errors:
[2020-09-09 23:32:41,929] [dftimewolf          ] ERROR    1: error from state: An unknown error occurred in module TimesketchExporter: Could not find a suitable TLS CA certificate bund
le, invalid path: True
[2020-09-09 23:32:41,929] [dftimewolf          ] ERROR    Traceback (most recent call last):
[2020-09-09 23:32:41,930] [dftimewolf          ] ERROR      File "/home/user1/dftimewolf/dftimewolf/dftimewolf/lib/state.py", line 170, in _SetupModuleThread
[2020-09-09 23:32:41,930] [dftimewolf          ] ERROR        module.SetUp(**new_args)
[2020-09-09 23:32:41,930] [dftimewolf          ] ERROR      File "/home/user1/dftimewolf/dftimewolf/dftimewolf/lib/exporters/timesketch.py", line 57, in SetUp
[2020-09-09 23:32:41,930] [dftimewolf          ] ERROR        self.state, token_password=token_password)
[2020-09-09 23:32:41,930] [dftimewolf          ] ERROR      File "/home/user1/dftimewolf/dftimewolf/dftimewolf/lib/timesketch_utils.py", line 50, in GetApiClient
[2020-09-09 23:32:41,931] [dftimewolf          ] ERROR        ts_client = assistant.get_client(token_password=token_password)
[2020-09-09 23:32:41,931] [dftimewolf          ] ERROR      File "/usr/local/lib/python3.6/dist-packages/timesketch_api_client/config.py", line 217, in get_client
[2020-09-09 23:32:41,931] [dftimewolf          ] ERROR        auth_mode=auth_mode,
[2020-09-09 23:32:41,931] [dftimewolf          ] ERROR      File "/usr/local/lib/python3.6/dist-packages/timesketch_api_client/client.py", line 106, in __init__
[2020-09-09 23:32:41,931] [dftimewolf          ] ERROR        client_secret=client_secret, auth_mode=auth_mode)
[2020-09-09 23:32:41,932] [dftimewolf          ] ERROR      File "/usr/local/lib/python3.6/dist-packages/timesketch_api_client/client.py", line 303, in _create_session
[2020-09-09 23:32:41,932] [dftimewolf          ] ERROR        self._set_csrf_token(session)
[2020-09-09 23:32:41,932] [dftimewolf          ] ERROR      File "/usr/local/lib/python3.6/dist-packages/timesketch_api_client/client.py", line 154, in _set_csrf_token
[2020-09-09 23:32:41,932] [dftimewolf          ] ERROR        response = session.get(self._host_uri)
[2020-09-09 23:32:41,932] [dftimewolf          ] ERROR      File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 543, in get
[2020-09-09 23:32:41,932] [dftimewolf          ] ERROR        return self.request('GET', url, **kwargs)
[2020-09-09 23:32:41,933] [dftimewolf          ] ERROR      File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 530, in request
[2020-09-09 23:32:41,933] [dftimewolf          ] ERROR        resp = self.send(prep, **send_kwargs)
[2020-09-09 23:32:41,933] [dftimewolf          ] ERROR      File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 643, in send

**Comment by kiddinn** [comment]
> @kiddinn Tried as requested.
> Getting the following error with "timesketch_import_client.py"
> 
> /usr/local/bin/timesketch_importer.py: line 14: A simple frontend to the Timesketch data importer.: command not found
> from: can't read /var/mail/**future**

`can't read /var/mail/**future**` that's odd... mail is not used anywhere... what system are you installing this on?

> /usr/local/bin/timesketch_importer.py: line 17: import: command not found
> /usr/local/bin/timesketch_importer.py: line 18: import: command not found
> /usr/local/bin/timesketch_importer.py: line 19: import: command not found
> /usr/local/bin/timesketch_importer.py: line 20: import: command not found
> /usr/local/bin/timesketch_importer.py: line 21: import: command not found

you are not running this as a python script.... how did you run the importer? `import` is not a bash command, this is a python script.

> from: can't read /var/mail/typing
> from: can't read /var/mail/timesketch_api_client
> from: can't read /var/mail/timesketch_api_client
> from: can't read /var/mail/timesketch_api_client
> from: can't read /var/mail/timesketch_api_client
> from: can't read /var/mail/timesketch_api_client
> from: can't read /var/mail/timesketch_import_client
> from: can't read /var/mail/timesketch_import_client
> /usr/local/bin/timesketch_importer.py: line 34: syntax error near unexpected token `level=os.environ.get' /usr/local/bin/timesketch_importer.py: line 34: `logging.basicConfig(level=os.environ.get('LOGLEVEL', 'INFO'))'

it seems like you are not running this using python

**Comment by kiddinn** [comment]
> More Errors related to Timesketch this time with TLS cert
> 
...
> [2020-09-09 23:32:41,903] [dftimewolf ] **CRITICAL An unknown error occurred in module TimesketchExporter: Could not find a suitable TLS CA certificate bundle, invalid path: True**
> [2020-09-09 23:32:41,929] [dftimewolf ] ERROR dfTimewolf encountered one or more errors:
> [2020-09-09 23:32:41,929] [dftimewolf ] ERROR 1: error from state: An unknown error occurred in module TimesketchExporter: Could not find a suitable TLS CA certificate bundle, invalid path: True
> [2020-09-09 23:32:41,929] [dftimewolf ] ERROR Traceback (most recent call last):
...
50, in GetApiClient
> [2020-09-09 23:32:41,931] [dftimewolf ] ERROR ts_client = assistant.get_client(token_password=token_password)
> [2020-09-09 23:32:41,931] [dftimewolf ] ERROR File "/usr/local/lib/python3.6/dist-packages/timesketch_api_client/config.py", line 217, in get_client
...
> [2020-09-09 23:32:41,932] [dftimewolf ] ERROR File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 543, in get
> [2020-09-09 23:32:41,932] [dftimewolf ] ERROR return self.request('GET', url, **kwargs)
> [2020-09-09 23:32:41,933] [dftimewolf ] ERROR File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 530, in request
> [2020-09-09 23:32:41,933] [dftimewolf ] ERROR resp = self.send(prep, **send_kwargs)
> [2020-09-09 23:32:41,933] [dftimewolf ] ERROR File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 643, in send

You can see that the issue is actually in the `session` file of the `requests` library. So this is the built-in `requests` library in python that is unable to establish a session to your TS server, due to 

>  Could not find a suitable TLS CA certificate bundle, invalid path: True

I can see similar issues here: https://github.com/ContinuumIO/anaconda-issues/issues/3916 

And I'm also seeing this error pop up in various sites, seemingly to point towards an invalid SSL certificate on the end server. So I'm wondering what sort of SSL cert do you have for your TS server?
