### ISSUE TITLE
setuptools_rust module not found when installing dependency libcst

### ISSUE THREAD

**Issue by sydp** [log2timeline/dftimewolf#573]
From PR check setuppy (ubuntu-latest, 3.10):

```Searching for libcst==0.4.1
Reading https://pypi.org/simple/libcst/
Downloading https://files.pythonhosted.org/packages/a4/6e/6fd5f3fc74a1401fa74f04afcd01e10f96e577ceb1ef3516c2e8d4d69736/libcst-0.4.1.tar.gz#sha256=961ab38c0ef318c384a287f1e4f877bb61ce93945f352b14b5dbbe7a317882b1
Best match: libcst 0.4.1
Processing libcst-0.4.1.tar.gz
Writing /tmp/easy_install-vx4bamu5/libcst-0.4.1/setup.cfg
Running libcst-0.4.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-vx4bamu5/libcst-0.4.1/egg-dist-tmp-nxla_ad1
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-vx4bamu5/libcst-0.4.1/setup.py", line 10, in <module>
    """Parse python requirements.
ModuleNotFoundError: No module named 'setuptools_rust'
```

**Comment by sydp** [comment]
Same issue as reported in #575
