### ISSUE TITLE
libcloudforensics e2e tests are failing

### ISSUE THREAD

**Issue by tomchop** [log2timeline/dftimewolf#614]
Seems to be related to the new curses changes:

```
+ PYTHONPATH=. python3 dftimewolf/cli/dftimewolf_recipes.py gcp_forensics <REDACTED>
Traceback (most recent call last):
  File "dftimewolf/cli/dftimewolf_recipes.py", line 481, in <module>
    if Main():
  File "dftimewolf/cli/dftimewolf_recipes.py", line 451, in Main
    cursesdisplaymanager.StartCurses()
  File "/tmp/workspace/dfTimewolf-libcloudforensics_e2e/dftimewolf/cli/curses_display_manager.py", line 151, in StartCurses
    self._stdscr = curses.initscr()
  File "/usr/lib/python3.8/curses/__init__.py", line 29, in initscr
    setupterm(term=_os.environ.get("TERM", "unknown"),
_curses.error: setupterm: could not find terminal
Build step 'Execute shell' marked build as failure
Sending e-mails
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
Finished: FAILURE
```

**Comment by ramo-j** [comment]
Presumably the tests just need the `DFTIMEWOLF_NO_CURSES` env var.

**Comment by ramo-j** [comment]
Build back to normal with that env var :ok_hand:

**Comment by tomchop** [comment]
Should we maybe catch this error and ask the user to add the env variable?
