### ISSUE TITLE
Error when uploading to Timesketch

### ISSUE THREAD

**Issue by jacobiusg** [log2timeline/dftimewolf#631]
I am getting a strange error when uploading to a Timsketch server. Command - Error

I have the url in the .dftimewolfrc file, it's just a standard http://ip/

dftimewolf upload_ts "base-rd-03-supertimeline.csv"

[2022-07-11 15:28:18,998] [dftimewolf          ] CRITICAL An unknown error occurred in module TimesketchExporter: Invalid URL '\x1bOA\x1bOA\x1bOA\x1bOA\x1bOB\x1bOBq\x1bOA\x1bOAclear': No schema supplied. Perhaps you meant http://AAAABBqAAclear?
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR    dfTimewolf encountered one or more errors:
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR    1: error from dftimewolf: An unknown error occurred in module TimesketchExporter: Invalid URL '\x1bOA\x1bOA\x1bOA\x1bOA\x1bOB\x1bOBq\x1bOA\x1bOAclear': No schema supplied. Perhaps you meant http://AAAABBqAAclear?
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR    Traceback (most recent call last):
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR      File "/home/jacobiusg/gitdir_python38/dftimewolf/dftimewolf/lib/state.py", line 314, in _SetupModuleThread
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR        self._RunModuleSetUp(module, **new_args)
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR      File "/home/jacobiusg/gitdir_python38/dftimewolf/dftimewolf/lib/state.py", line 667, in _RunModuleSetUp
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR        module.SetUp(**new_args)
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR      File "/home/jacobiusg/gitdir_python38/dftimewolf/dftimewolf/lib/exporters/timesketch.py", line 76, in SetUp
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR        self.timesketch_api = timesketch_utils.GetApiClient(
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR      File "/home/jacobiusg/gitdir_python38/dftimewolf/dftimewolf/lib/timesketch_utils.py", line 58, in GetApiClient
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR        ts_client = assistant.get_client(token_password=token_password)
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR      File "/home/jacobiusg/.local/lib/python3.10/site-packages/timesketch_api_client/config.py", line 171, in get_client
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR        return client.TimesketchApi(
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR      File "/home/jacobiusg/.local/lib/python3.10/site-packages/timesketch_api_client/client.py", line 108, in __init__
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR        self.session = self._create_session(
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR      File "/home/jacobiusg/.local/lib/python3.10/site-packages/timesketch_api_client/client.py", line 314, in _create_session
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR        self._set_csrf_token(session)
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR      File "/home/jacobiusg/.local/lib/python3.10/site-packages/timesketch_api_client/client.py", line 163, in _set_csrf_token
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR        response = session.get(self._host_uri)
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR      File "/home/jacobiusg/.local/lib/python3.10/site-packages/requests/sessions.py", line 555, in get
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR        return self.request('GET', url, **kwargs)
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR      File "/home/jacobiusg/.local/lib/python3.10/site-packages/requests/sessions.py", line 528, in request
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR        prep = self.prepare_request(req)
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR      File "/home/jacobiusg/.local/lib/python3.10/site-packages/requests/sessions.py", line 456, in prepare_request
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR        p.prepare(
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR      File "/home/jacobiusg/.local/lib/python3.10/site-packages/requests/models.py", line 316, in prepare
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR        self.prepare_url(url, params)
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR      File "/home/jacobiusg/.local/lib/python3.10/site-packages/requests/models.py", line 390, in prepare_url
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR        raise MissingSchema(error)
[2022-07-11 15:28:18,999] [dftimewolf          ] ERROR    requests.exceptions.MissingSchema: Invalid URL '\x1bOA\x1bOA\x1bOA\x1bOA\x1bOB\x1bOBq\x1bOA\x1bOAclear': No schema supplied. Perhaps you meant http://AAAABBqAAclear?

**Comment by tomchop** [comment]
That's strange indeed. Did you tweak the recipe (json file) in any way? What steps did you follow to authenticate with Timesketch?

**Comment by jacobiusg** [comment]
Just user/pass but did not get that far it aborted

**Comment by tomchop** [comment]
Looks like it's coming from here https://github.com/google/timesketch/blob/master/api_client/python/timesketch_api_client/config.py#L182 (so not dfTimewolf per se, but rather the upstream dependency on `timesketch_api_client`. My impression is that this is caused by a corrupt token file, I'd recommend deleting your `.timesketchrc` file (which contains credentials to timesketch) and trying again.

**Comment by jacobiusg** [comment]
Okay thanks for the help, I'll do just that and see if it works.

**Comment by jacobiusg** [comment]
That worked, Thanks for looking at this.
