### ISSUE TITLE
AWS creds in Env vars not supported in aws_logging_collect recipe

### ISSUE THREAD

**Issue by ramo-j** [log2timeline/dftimewolf#709]
AWS SDKs and command line tools support sourcing credentials from environment variables[0]. However, in DFTW when env vars are present, the AWS cred preflight module, and AWSLogsCollector (and probably other AWS modules) still look for a default profile and fail when none is configured. If no profile is specified, env vars should be used (if found.)

```
$ env | grep AWS
AWS_SECRET_ACCESS_KEY=<scrubbed>
AWS_ACCESS_KEY_ID=AKIA<scrubbed>
$ DFTIMEWOLF_NO_CURSES=1 poetry run python3 -m dftimewolf.cli.dftimewolf_recipes aws_logging_collect
[2023-01-30 03:31:51,427] [dftimewolf          ] DEBUG    Logging to stdout and /tmp/dftimewolf-run-20230130_033151_v3bsnf2k.log
[2023-01-30 03:31:51,427] [dftimewolf          ] SUCCESS  Success!
[2023-01-30 03:31:51,427] [dftimewolf          ] DEBUG    Recipe data path: /home/ramoj_google_com/code/dftimewolf/data
[2023-01-30 03:31:51,427] [dftimewolf          ] DEBUG    Configuration loaded from: /home/ramoj_google_com/code/dftimewolf/data/config.json
[2023-01-30 03:31:51,445] [dftimewolf          ] INFO     Loading recipe aws_logging_collect...
[2023-01-30 03:31:51,445] [dftimewolf          ] DEBUG    Loading module AWSLogsCollector from dftimewolf.lib.collectors.aws_logging
[2023-01-30 03:31:51,550] [dftimewolf          ] DEBUG    Loading module AWSAccountCheck from dftimewolf.lib.preflights.cloud_token
[2023-01-30 03:31:51,551] [dftimewolf          ] INFO     Loaded recipe aws_logging_collect with 2 modules
[2023-01-30 03:31:51,551] [dftimewolf          ] DEBUG    AWSAccountCheck:
[2023-01-30 03:31:51,551] [dftimewolf          ] DEBUG      profile_name   'default'
[2023-01-30 03:31:51,551] [dftimewolf          ] DEBUG    AWSLogsCollector:
[2023-01-30 03:31:51,551] [dftimewolf          ] DEBUG      profile_name   'default'
[2023-01-30 03:31:51,551] [dftimewolf          ] DEBUG      query_filter   None
[2023-01-30 03:31:51,551] [dftimewolf          ] DEBUG      start_time     None
[2023-01-30 03:31:51,551] [dftimewolf          ] DEBUG      end_time       None
[2023-01-30 03:31:51,551] [dftimewolf          ] DEBUG    
[2023-01-30 03:31:51,551] [dftimewolf          ] INFO     Running preflights...
[2023-01-30 03:31:51,557] [AWSAccountCheck     ] CRITICAL Profile not found, see https://boto3.amazonaws.com/v1/documentation/api/latest/guide/quickstart.html#configuration
Traceback (most recent call last):
  File "/home/ramoj_google_com/code/dftimewolf/dftimewolf/lib/preflights/cloud_token.py", line 67, in SetUp
    session = boto_session.Session(profile_name=profile_name)
  File "/home/ramoj_google_com/.cache/pypoetry/virtualenvs/dftimewolf-doFXGYUB-py3.9/lib/python3.9/site-packages/boto3/session.py", line 90, in __init__
    self._setup_loader()
  File "/home/ramoj_google_com/.cache/pypoetry/virtualenvs/dftimewolf-doFXGYUB-py3.9/lib/python3.9/site-packages/boto3/session.py", line 131, in _setup_loader
    self._loader = self._session.get_component('data_loader')
  File "/home/ramoj_google_com/.cache/pypoetry/virtualenvs/dftimewolf-doFXGYUB-py3.9/lib/python3.9/site-packages/botocore/session.py", line 771, in get_component
    return self._components.get_component(name)
  File "/home/ramoj_google_com/.cache/pypoetry/virtualenvs/dftimewolf-doFXGYUB-py3.9/lib/python3.9/site-packages/botocore/session.py", line 1081, in get_component
    self._components[name] = factory()
  File "/home/ramoj_google_com/.cache/pypoetry/virtualenvs/dftimewolf-doFXGYUB-py3.9/lib/python3.9/site-packages/botocore/session.py", line 182, in <lambda>
    lambda: create_loader(self.get_config_variable('data_path')),
  File "/home/ramoj_google_com/.cache/pypoetry/virtualenvs/dftimewolf-doFXGYUB-py3.9/lib/python3.9/site-packages/botocore/session.py", line 305, in get_config_variable
    return self.get_component('config_store').get_config_variable(
  File "/home/ramoj_google_com/.cache/pypoetry/virtualenvs/dftimewolf-doFXGYUB-py3.9/lib/python3.9/site-packages/botocore/configprovider.py", line 426, in get_config_variable
    return provider.provide()
  File "/home/ramoj_google_com/.cache/pypoetry/virtualenvs/dftimewolf-doFXGYUB-py3.9/lib/python3.9/site-packages/botocore/configprovider.py", line 628, in provide
    value = provider.provide()
  File "/home/ramoj_google_com/.cache/pypoetry/virtualenvs/dftimewolf-doFXGYUB-py3.9/lib/python3.9/site-packages/botocore/configprovider.py", line 718, in provide
    scoped_config = self._session.get_scoped_config()
  File "/home/ramoj_google_com/.cache/pypoetry/virtualenvs/dftimewolf-doFXGYUB-py3.9/lib/python3.9/site-packages/botocore/session.py", line 404, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (default) could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ramoj_google_com/code/dftimewolf/dftimewolf/cli/dftimewolf_recipes.py", line 521, in <module>
    if Main():
  File "/home/ramoj_google_com/code/dftimewolf/dftimewolf/cli/dftimewolf_recipes.py", line 494, in Main
    return RunTool()
  File "/home/ramoj_google_com/code/dftimewolf/dftimewolf/cli/dftimewolf_recipes.py", line 459, in RunTool
    tool.RunPreflights()
  File "/home/ramoj_google_com/code/dftimewolf/dftimewolf/cli/dftimewolf_recipes.py", line 304, in RunPreflights
    self._state.RunPreflights()
  File "/home/ramoj_google_com/code/dftimewolf/dftimewolf/lib/state.py", line 520, in RunPreflights
    self._RunModuleSetUp(preflight, **new_args)
  File "/home/ramoj_google_com/code/dftimewolf/dftimewolf/lib/state.py", line 366, in _RunModuleSetUp
    module.SetUp(**new_args)
  File "/home/ramoj_google_com/code/dftimewolf/dftimewolf/lib/preflights/cloud_token.py", line 71, in SetUp
    self.ModuleError(
  File "/home/ramoj_google_com/code/dftimewolf/dftimewolf/lib/module.py", line 118, in ModuleError
    raise error
dftimewolf.lib.errors.DFTimewolfError: Profile not found, see https://boto3.amazonaws.com/v1/documentation/api/latest/guide/quickstart.html#configuration
```

[0] https://docs.aws.amazon.com/sdkref/latest/guide/environment-variables.html

**Comment by ramo-j** [comment]
Recipe problem, not a mocule problem: `aws_logging_collect` recipe has `"default"` as the default value for the aws_profile, but if changed to None, creds come from the environment correctly.
