### ISSUE TITLE
Error getting Turbinia results

### ISSUE THREAD

**Issue by aarontp** [log2timeline/dftimewolf#789]
Getting this error in a run of ` dftimewolf gcp_turbinia_disk_copy_ts` when using HEAD from dftimewolf and Turbinia.  This is probably related to the upstream change https://github.com/google/turbinia/pull/1357 and may need some changes to the way the Turbinia api lib is called

```
[2023-10-07 17:52:31,531] [dftimewolf.state    ] CRITICAL An unknown error occurred in module TurbiniaGCPProcessor: Error! Please call the get_task_output_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data
[2023-10-07 17:52:31,533] [dftimewolf.state    ] INFO     Module TurbiniaGCPProcessor finished execution
[2023-10-07 17:52:31,533] [dftimewolf.state    ] CRITICAL Aborting execution of TimesketchExporter due to previous errors
[2023-10-07 17:52:31,533] [dftimewolf.state    ] ERROR    dfTimewolf encountered one or more errors:
[2023-10-07 17:52:31,534] [dftimewolf.state    ] ERROR    1: error from dftimewolf: An unknown error occurred in module TurbiniaGCPProcessor: Error! Please call the get_task_output_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data
[2023-10-07 17:52:31,534] [dftimewolf.state    ] ERROR    Traceback (most recent call last):
[2023-10-07 17:52:31,534] [dftimewolf.state    ] ERROR      File "/home/aaronpeterson/src/turbinia-talks/src/dftimewolf/dftimewolf/lib/state.py", line 474, in _RunModuleThread
[2023-10-07 17:52:31,534] [dftimewolf.state    ] ERROR        self._HandleFuturesFromThreadedModule(futures, runtime_name)
[2023-10-07 17:52:31,534] [dftimewolf.state    ] ERROR      File "/home/aaronpeterson/src/turbinia-talks/src/dftimewolf/dftimewolf/lib/state.py", line 426, in _HandleFuturesFromThreadedModule
[2023-10-07 17:52:31,534] [dftimewolf.state    ] ERROR        raise fut.exception()  # type: ignore
[2023-10-07 17:52:31,534] [dftimewolf.state    ] ERROR        ^^^^^^^^^^^^^^^^^^^^^
[2023-10-07 17:52:31,534] [dftimewolf.state    ] ERROR      File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
[2023-10-07 17:52:31,534] [dftimewolf.state    ] ERROR        result = self.fn(*self.args, **self.kwargs)
[2023-10-07 17:52:31,534] [dftimewolf.state    ] ERROR                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-10-07 17:52:31,534] [dftimewolf.state    ] ERROR      File "/home/aaronpeterson/src/turbinia-talks/src/dftimewolf/dftimewolf/lib/processors/turbinia_gcp.py", line 214, in Process
[2023-10-07 17:52:31,534] [dftimewolf.state    ] ERROR        local_path = self.DownloadFilesFromAPI(task, path)
[2023-10-07 17:52:31,534] [dftimewolf.state    ] ERROR                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-10-07 17:52:31,534] [dftimewolf.state    ] ERROR      File "/home/aaronpeterson/src/turbinia-talks/src/dftimewolf/dftimewolf/lib/processors/turbinia_base.py", line 173, in DownloadFilesFromAPI
[2023-10-07 17:52:31,534] [dftimewolf.state    ] ERROR        api_response = api_instance.get_task_output(
[2023-10-07 17:52:31,534] [dftimewolf.state    ] ERROR                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-10-07 17:52:31,534] [dftimewolf.state    ] ERROR      File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
[2023-10-07 17:52:31,535] [dftimewolf.state    ] ERROR      File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
[2023-10-07 17:52:31,535] [dftimewolf.state    ] ERROR      File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
[2023-10-07 17:52:31,535] [dftimewolf.state    ] ERROR      File "/home/aaronpeterson/src/turbinia-talks/src/turbinia/turbinia/api/client/turbinia_api_lib/api/turbinia_request_results_api.py", line 214, in get_task_output
[2023-10-07 17:52:31,535] [dftimewolf.state    ] ERROR        raise ValueError(message)
[2023-10-07 17:52:31,535] [dftimewolf.state    ] ERROR    ValueError: Error! Please call the get_task_output_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data
[2023-10-07 17:52:31,535] [dftimewolf.state    ] ERROR    
[2023-10-07 17:52:31,535] [dftimewolf.state    ] CRITICAL One or more unexpected errors occurred.
[2023-10-07 17:52:31,535] [dftimewolf.state    ] CRITICAL Please consider opening an issue: https://github.com/log2timeline/dftimewolf/issues/new
[2023-10-07 17:52:31,535] [dftimewolf          ] CRITICAL Critical error found. Aborting.

```

**Comment by aarontp** [comment]
Pretty sure this was fixed in #804
