### ISSUE TITLE
GRRHuntArtifactCollector recipe broken

### ISSUE THREAD

**Issue by Onager** [log2timeline/dftimewolf#96]
Running module GRRHuntArtifactCollector
Traceback (most recent call last):
  File "dftimewolf/cli/dftimewolf_recipes.py", line 125, in <module>
    main()
  File "dftimewolf/cli/dftimewolf_recipes.py", line 113, in main
    module.setup(**new_args)
TypeError: setup() got an unexpected keyword argument 'verify'

**Comment by tomchop** [comment]
Still broken
